package com.app.chatserver.enums;

public enum ServerChatErrors {
    NEW_MESSAGE_INCORRECT,
    CHAT_ROOM_NOT_FOUND,
    USER_NOT_FOUND,
    DELETED_CHAT_ROOM_NOT_FOUND,
    MESSAGE_NOT_FOUND,
    INVALID_JWT_SIGNATURE,
    INVALID_JWT_TOKEN,
    EXPIRED_TOKEN,
    UNSUPPORTED_JWT_TOKEN,
    CLAIMS_IS_EMPTY,
    ACCESS_DENIED,
    NO_MEMBERS_IN_CHAT,
    MEMBER_USER_NOT_FOUND,
    CHAT_ROOM_NOT_SEND,
    POST_NOT_FOUND,
    LIKED_POSTS_NOT_FOUND,
    SUBSCRIBE_NOT_FOUND,
    FEED_NOT_FOUND,
    FORWARD_COMMENT_NOT_FOUND,
    COMMENT_NOT_FOUND,
    ALREADY_LIKED,
    ALREADY_SUBSCRIBED,
    MEDIA_NOT_FOUND,
    BLACK_LIST_NOT_FOUND,

    MEDIA_TYPE_REQUIRED

}
